// export const GetCards = 
// [
//     { "id": "Ace", "suite": "Spades", "value": 1 },
//     { "id": "2", "suite": "Spades", "value": 2 },
//     { "id": "3", "suite": "Spades", "value": 3 },
//     { "id": "4", "suite": "Spades", "value": 4 },
//     { "id": "5", "suite": "Spades", "value": 5 },
//     { "id": "6", "suite": "Spades", "value": 6 },
//     { "id": "7", "suite": "Spades", "value": 7 },
//     { "id": "8", "suite": "Spades", "value": 8 },
//     { "id": "9", "suite": "Spades", "value": 9 },
//     { "id": "10", "suite": "Spades", "value": 10 },
//     { "id": "Jack", "suite": "Spades", "value": 11 },
//     { "id": "Queen", "suite": "Spades", "value": 12 },
//     { "id": "King", "suite": "Spades", "value": 13 },

//     { "id": "Ace", "suite": "Hearts", "value": 1 },
//     { "id": "2", "suite": "Hearts", "value": 2 },
//     { "id": "3", "suite": "Hearts", "value": 3 },
//     { "id": "4", "suite": "Hearts", "value": 4 },
//     { "id": "5", "suite": "Hearts", "value": 5 },
//     { "id": "6", "suite": "Hearts", "value": 6 },
//     { "id": "7", "suite": "Hearts", "value": 7 },
//     { "id": "8", "suite": "Hearts", "value": 8 },
//     { "id": "9", "suite": "Hearts", "value": 9 },
//     { "id": "10", "suite": "Hearts", "value": 10 },
//     { "id": "Jack", "suite": "Hearts", "value": 11 },
//     { "id": "Queen", "suite": "Hearts", "value": 12 },
//     { "id": "King", "suite": "Hearts", "value": 13 },

//     { "id": "Ace", "suite": "Diamonds", "value": 1 },
//     { "id": "2", "suite": "Diamonds", "value": 2 },
//     { "id": "3", "suite": "Diamonds", "value": 3 },
//     { "id": "4", "suite": "Diamonds", "value": 4 },
//     { "id": "5", "suite": "Diamonds", "value": 5 },
//     { "id": "6", "suite": "Diamonds", "value": 6 },
//     { "id": "7", "suite": "Diamonds", "value": 7 },
//     { "id": "8", "suite": "Diamonds", "value": 8 },
//     { "id": "9", "suite": "Diamonds", "value": 9 },
//     { "id": "10", "suite": "Diamonds", "value": 10 },
//     { "id": "Jack", "suite": "Diamonds", "value": 11 },
//     { "id": "Queen", "suite": "Diamonds", "value": 12 },
//     { "id": "King", "suite": "Diamonds", "value": 13 },

//     { "id": "Ace", "suite": "Clubs", "value": 1 },
//     { "id": "2", "suite": "Clubs", "value": 2 },
//     { "id": "3", "suite": "Clubs", "value": 3 },
//     { "id": "4", "suite": "Clubs", "value": 4 },
//     { "id": "5", "suite": "Clubs", "value": 5 },
//     { "id": "6", "suite": "Clubs", "value": 6 },
//     { "id": "7", "suite": "Clubs", "value": 7 },
//     { "id": "8", "suite": "Clubs", "value": 8 },
//     { "id": "9", "suite": "Clubs", "value": 9 },
//     { "id": "10", "suite": "Clubs", "value": 10 },
//     { "id": "Jack", "suite": "Clubs", "value": 11 },
//     { "id": "Queen", "suite": "Clubs", "value": 12 },
//     { "id": "King", "suite": "Clubs", "value": 13 }
// ]